### ISSUE TITLE
XDown 使用技巧 | 百度网盘直链下载助手

### ISSUE THREAD

**Issue by syhyz1990** [syhyz1990/baiduyun#269]
https://www.baiduyun.wiki/zh-cn/xdown.html 

 🖖油猴脚本 一个脚本搞定百度网盘下载

**Comment by xdown-org** [comment]
@syhyz1990   没有替换呀,还是那个15分钟的视频,新视频是7分钟的

**Comment by lffw001** [comment]
@xdown-org  xdown win10 LTSC 64位 打开软件提示配置文件打开失败是什么问题

**Comment by xdown-org** [comment]
`C:\Users\用户名\AppData\Local\.xdown`

清空里面的所有文件

**Comment by lffw001** [comment]
> @xdown-org
> @lffw001
> `C:\Users\用户名\AppData\Local\.xdown`
> 
> 清空里面的所有文件
试了还是同样提示

**Comment by 849567693** [comment]
您好，我使用XDown下载文件，显示异常，没法下载，是不是我的账号被限制了呀？

**Comment by xdown-org** [comment]
@849567693   使用免登陆下载,

**Comment by xdown-org** [comment]
@lffw001 你版本号是多少

**Comment by lffw001** [comment]
> @xdown-org
> @lffw001 你版本号是多少

1.03~1.05都一样的提示

**Comment by xdown-org** [comment]
@lffw001 右键 以管理员权限运行试试

**Comment by 849567693** [comment]
免登陆不能下文件夹哎，有点麻烦哈哈哈




------------------ 原始邮件 ------------------
发件人: "xdown-org"<notifications@github.com>; 
发送时间: 2019年9月23日(星期一) 晚上8:29
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>; 
抄送: "&#x1F43E; 猫忘了鱼尾纱 &#x1F433;"<849567693@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)




@849567693   使用免登陆下载,

**Comment by xdown-org** [comment]
@lffw001 你系统账号有中文吗?
你把
`C:\Users\用户名\AppData\Local\.xdown`

里面文件打包发我

gatebyebye@outlook.com

**Comment by lffw001** [comment]
> @xdown-org
>  @lffw001 你系统账号有中文吗?
> 你把
> `C:\Users\用户名\AppData\Local\.xdown`
> 
> 里面文件打包发我
> 
> gatebyebye@outlook.com

是的有中文，配置文件已经发过去了，感谢您的耐心回复

**Comment by lffw001** [comment]
> @xdown-org
> @lffw001 右键 以管理员权限运行试试

还是失败

**Comment by xdown-org** [comment]
@lffw001 给你发文件了,替换看看

**Comment by lffw001** [comment]
> @xdown-org
> @lffw001 给你发文件了,替换看看

感谢大牛，现在可以使用了

**Comment by deepwebhacker** [comment]
下载文件提示异常，大佬

**Comment by deepwebhacker** [comment]
> @xdown-org
我的配置文件已发，大佬。
最新版本下载提示异常

**Comment by irislian** [comment]
> @xdown-org
> @849567693   使用免登陆下载,

分享链接打开后点击下载助手显示aria链接 提示要登录才能获取

**Comment by shuiruoshan** [comment]
大神。下文件都提示异常

**Comment by qqq215** [comment]
不知出了什么问题，分享以无法下载，XDown提示异常，Internet Download Manager提示无权下载。非常感谢提供这么好的工具。

**Comment by poxiaozhiguang** [comment]
我这也有问题，点击 极速下载 后输入验证码，然后弹不出链接。。昨天还能用的

**Comment by ShuiTunGao** [comment]
更新了1.005，下载提示异常

**Comment by NicerOuZa** [comment]
免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事

**Comment by NicerOuZa** [comment]
@xdown-org求大佬看看留言解决一下

**Comment by poxiaozhiguang** [comment]
那你知道如何解决吗。普通连接的速度不行啊，我应该是被关小黑屋了。------------------ 原始邮件 ------------------
发件人: "NicerOuZa"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 下午4:45
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "poxiaozhiguang"<948710507@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)



免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事
 
&mdash;

**Comment by NicerOuZa** [comment]
我现在都下载不了，xdown一用就提示我异常，你是怎么用普通链接下的.......




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"poxiaozhiguang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月26日(星期四) 下午4:49
收件人:&nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送:&nbsp;"378292586"<378292586@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)



那你知道如何解决吗。普通连接的速度不行啊，我应该是被关小黑屋了。------------------ 原始邮件 ------------------ 
 发件人: "NicerOuZa"<notifications@github.com&gt; 
 发送时间: 2019年9月26日(星期四) 下午4:45 
 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
 抄送: "poxiaozhiguang"<948710507@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269) 
 
 
 
 免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事 
   
 &amp;mdash;

**Comment by poxiaozhiguang** [comment]
最开始我是用普通连接的。然后速度不行了。又换的免登录下载。现在免登录都不行了。我就彻底废了啊_(:з」∠)_------------------ 原始邮件 ------------------
发件人: "NicerOuZa"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 下午4:50
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "poxiaozhiguang"<948710507@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)


我现在都下载不了，xdown一用就提示我异常，你是怎么用普通链接下的....... 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"poxiaozhiguang"<notifications@github.com&gt;; 
 发送时间:&nbsp;2019年9月26日(星期四) 下午4:49 
 收&#x4EF6;人:&nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
 抄送:&nbsp;"378292586"<378292586@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题:&nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269) 
 
 
 
 那你知道如何解决吗。普通连接的速度不行啊，我应该是被关小黑屋了。------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "NicerOuZa"<notifications@github.com&gt;  
  发送时间: 2019年9月26日(星期四) 下午4:45  
  收&#x4EF6;人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;  
  抄送: "poxiaozhiguang"<948710507@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;  
  主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)  
   
   
   
  免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事  
     
  &amp;mdash;  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by NicerOuZa** [comment]
应该是最近百度又开始查了，等官方更新吧...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"poxiaozhiguang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月26日(星期四) 下午4:54
收件人:&nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;
抄送:&nbsp;"378292586"<378292586@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)



最开始我是用普通连接的。然后速度不行了。又换的免登录下载。现在免登录都不行了。我就彻底废了啊_(:з」∠)_------------------ 原始邮件 ------------------ 
 发件人: "NicerOuZa"<notifications@github.com&gt; 
 发送时间: 2019年9月26日(星期四) 下午4:50 
 收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
 抄送: "poxiaozhiguang"<948710507@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269) 
 
 
 我现在都下载不了，xdown一用就提示我异常，你是怎么用普通链接下的.......  
   
   
   
   
  ------------------&amp;nbsp;原始邮&amp;#x4EF6;&amp;nbsp;------------------  
  发&amp;#x4EF6;人:&amp;nbsp;"poxiaozhiguang"<notifications@github.com&amp;gt;;  
  发送时间:&amp;nbsp;2019年9月26日(星期四) 下午4:49  
  收&amp;#x4EF6;人:&amp;nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&amp;gt;;  
  抄送:&amp;nbsp;"378292586"<378292586@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;  
  主题:&amp;nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)  
   
   
   
  那你知道如何解决吗。普通连接的速度不行啊，我应该是被关小黑屋了。------------------ 原始邮&amp;#x4EF6; ------------------   
   发&amp;#x4EF6;人: "NicerOuZa"<notifications@github.com&amp;gt;   
   发送时间: 2019年9月26日(星期四) 下午4:45   
   收&amp;#x4EF6;人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&amp;gt;;   
   抄送: "poxiaozhiguang"<948710507@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;   
   主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)   
     
     
     
   免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事   
       
   &amp;amp;mdash;   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 &amp;mdash;

**Comment by poxiaozhiguang** [comment]
嗯嗯，我现在也不知道怎么办，这两天刚好要下视频，尴尬😓------------------ 原始邮件 ------------------
发件人: "NicerOuZa"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 下午4:55
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "poxiaozhiguang"<948710507@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)


应该是最近百度又开始查了，等官方更新吧... 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"poxiaozhiguang"<notifications@github.com&gt;; 
 发送时间:&nbsp;2019年9月26日(星期四) 下午4:54 
 收&#x4EF6;人:&nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
 抄送:&nbsp;"378292586"<378292586@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题:&nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269) 
 
 
 
 最开始我是用普通连接的。然后速度不行了。又换的免登录下载。现在免登录都不行了。我就彻底废了啊_(:з」∠)_------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "NicerOuZa"<notifications@github.com&gt;  
  发送时间: 2019年9月26日(星期四) 下午4:50  
  收&#x4EF6;人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;;  
  抄送: "poxiaozhiguang"<948710507@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;  
  主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)  
   
   
  我现在都下载不了，xdown一用就提示我异常，你是怎么用普通链接下的.......   
     
     
     
     
   ------------------&amp;nbsp;原始邮&amp;#x4EF6;&amp;nbsp;------------------   
   发&amp;#x4EF6;人:&amp;nbsp;"poxiaozhiguang"<notifications@github.com&amp;gt;;   
   发送时间:&amp;nbsp;2019年9月26日(星期四) 下午4:49   
   收&amp;#x4EF6;人:&amp;nbsp;"syhyz1990/baiduyun"<baiduyun@noreply.github.com&amp;gt;;   
   抄送:&amp;nbsp;"378292586"<378292586@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;   
   主题:&amp;nbsp;Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)   
     
     
     
   那你知道如何解决吗。普通连接的速度不行啊，我应该是被关小黑屋了。------------------ 原始邮&amp;#x4EF6; ------------------    
    发&amp;#x4EF6;人: "NicerOuZa"<notifications@github.com&amp;gt;    
    发送时间: 2019年9月26日(星期四) 下午4:45    
    收&amp;#x4EF6;人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&amp;gt;;    
    抄送: "poxiaozhiguang"<948710507@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;    
    主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)    
       
       
       
    免登陆链接现在不行了，百度网盘要求必须登录账户才能显示，我也是xdown提示异常然后idm提示无权下载，不知道咋回事    
         
    &amp;amp;mdash;    
    You are receiving this because you commented.    
    Reply to this email directly, view it on GitHub, or mute the thread.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  &amp;mdash;  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by othpark** [comment]
xdown-1.0.0.5 - 修复下载中异常问题.zip里面没有xdown.exe咋打开程序啊？

**Comment by tlovescc** [comment]
和以上的同学一样，获取了链接地址后，xdown下载显示异常。IDM也下载不了。

**Comment by wsy531156949** [comment]
请问现在是不是不支持免登陆下载了？我一旦退出账号打开分享链接，下载助手就只有保存后下载这一个选项

**Comment by MRsun-iwnl** [comment]
为什么我连下载都没有只有保存后下载

**Comment by poxiaozhiguang** [comment]
几天没用了。不知道发生了什么，我之前就已经不能用了，和你并没有本质区别_(:з」∠)_------------------ 原始邮件 ------------------
发件人: "MRsun-iwnl"<notifications@github.com>
发送时间: 2019年9月30日(星期一) 凌晨0:05
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com>;
抄送: "poxiaozhiguang"<948710507@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)



为什么我连下载都没有只有保存后下载
 
&mdash;

**Comment by paradise-x** [comment]
就，奇怪我昨天刚接触xdown，是在单位电脑上用的，顺利下载，今天寻思回家用用吧？结果就跟下面都异常一周了的同学们一样提示的是异常，不能下载（然而也有一些能下载的）

**Comment by myf2001** [comment]
> 更新后xdown依旧异常

**Comment by Hugo342523** [comment]
Xdown不能记住设定的下载保存路径。每次下载都要重新设置保存路径

**Comment by lzgyc** [comment]
升级百度助手2.9.1，xdown1.0.0.7后，现在下载百度网盘文件的速度只有2.4MB左右，过去能达到5MB左右，要怎么提高速度？lzgyc@sina.com

**Comment by W766372627** [comment]
Xdown现在只能单文件下载了，批量下载错误了

**Comment by baowenqing** [comment]
大佬 Xdown可以支持文件夹下载吗？ 当账号被限速的时候且文件比较多的时候 只能采用免登陆方式  一个个复制去下载 效率有点慢 呜呜呜~~~

**Comment by SunShRui** [comment]
mac 版什么时候提供呢？

**Comment by poxiaozhiguang** [comment]
现在百度会识别浏览器的插件了吗，不禁用这个下载助手就没办法打开百度网盘啊。。。有同样的小伙伴吗

**Comment by ok3777** [comment]
> @xdown-org
> @849567693   使用免登陆下载,

免登录 不能批量下载啊 超过300m就不能了蛋疼..

**Comment by JackyXXX** [comment]
用了baiduyun.wiki解析后，再用xdown下载Aria2链接显示异常，无法下载，怎么办？

**Comment by maijianhuan** [comment]
登录的下载链接。。速度好慢。。免登录那个下载链接 又显示异常。。

**Comment by dajiangyou11** [comment]
现在是用不了了吗？一直显示异常

**Comment by RocmanZero** [comment]
syhyz1990大大在吗？ 今天10月22号开始用xdown下载全显示异常，这样解析了连接也没用了......

**Comment by zhanghao-1994** [comment]
xdown下载一直异常，idm解析不出文件类型，也不能下载了

**Comment by Hugo342523** [comment]
> xdown下载一直异常，idm解析不出文件类型，也不能下载了

刚才试了一下，确实如此！！！急需修复

**Comment by Hugo342523** [comment]
网盘解析能成功，但是解析出来的下载链接是无效的，xdown和idm都不行

**Comment by Hugo342523** [comment]
> 网盘解析能成功，但是解析出来的下载链接是无效的，xdown和idm都不行

刚才又试了一下，登陆能用；免登录解析挂了

**Comment by Hugo342523** [comment]
> > xdown下载一直异常，idm解析不出文件类型，也不能下载了
> 
> 刚才试了一下，确实如此！！！急需修复

刚才又试了一下，登陆能用；免登录解析挂了

**Comment by Inotia-216** [comment]
我也是下载异常= =

**Comment by Inotia-216** [comment]
用的是xdown

**Comment by dany50001** [comment]
請問一下 現在Xdown v1.0.0.7 失效了? 一直都出現异常 無法下載 ...還是 我少安裝插件 程式??

**Comment by shadowdragon1123** [comment]
> @Hugo342523
> > > xdown下载一直异常，idm解析不出文件类型，也不能下载了
> > 
> > 刚才试了一下，确实如此！！！急需修复
> 
> 刚才又试了一下，登陆能用；免登录解析挂了

xdown登陆能用是什么？自己网盘里的ARIA2链接吗

**Comment by UFO-13** [comment]
xdown下载异常,崩盘了？

**Comment by linfeng0169** [comment]
我的WIN8系统打开XDOWN就出错，根本进不去界面……

**Comment by Hafeez-zhf3536** [comment]
xdown失效了吗？ 免登录提取链接，关注后输入授权码后 显示未知错误呀

**Comment by raymondaltman** [comment]
下载的时候总显示异常怎么解决呢？

**Comment by Yichengxuan** [comment]
用免登录的链接在Xdown软件下载的时候经常异常，无法正常下载。请问这是被百度后台限制了吗？
如果是的话，请问有解决办法吗？

**Comment by zhanghao-1994** [comment]
现在免登录可以用

**Comment by dany50001** [comment]
請問 我用线解析一直 叫我輸入今日授權碼 要怎麼用呢?要怎麼到 官方公告回覆 授權??

**Comment by zhanghao-1994** [comment]
> @dany50001
> 請問 我用线解析一直 叫我輸入今日授權碼 要怎麼用呢?要怎麼到 官方公告回覆 授權?? 

提示授权的页面会有二维码，微信扫码关注。

**Comment by dany50001** [comment]
恩 那再請教各位大大 這個在线解析 檔案大小是不能超過3g 以上? 有上辦法可以解決 ?

**Comment by uyoungco** [comment]
有mac版吗？

**Comment by Hafeez-zhf3536** [comment]
免登路连接在xdown里经常异常啊，不能下载啊

**Comment by abc598300612** [comment]
为什么免登陆下载 xdown显示异常

**Comment by shadowdragon1123** [comment]
尝试了几次，免登陆的aria链接在xdown里还是显示异常

**Comment by Cyberavater** [comment]
我按了红色按钮，但是没有用

**Comment by Zerlindadahua** [comment]
之前xdown还能用，不知道为啥现在不能了...

**Comment by srx00000** [comment]
台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常

**Comment by abc598300612** [comment]
> 台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常

大陆用户也一样

**Comment by Hugo342523** [comment]
> 台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常

台湾用户富裕，情况还好一点，可以开会员嘛。大陆用户就苦逼了，没钱开会员啊

**Comment by Hugo342523** [comment]
30RMB一个月，能买好多茶叶蛋和榨菜呢😁😁😁

**Comment by abc598300612** [comment]
哎 一把辛酸泪 前两天为了下资料 果断交月供

**Comment by srx00000** [comment]
> > 台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常
> 
> 台湾用户富裕，情况还好一点，可以开会员嘛。大陆用户就苦逼了，没钱开会员啊

問題是百度盤把台灣ip給牆了

**Comment by Hugo342523** [comment]
> > > 台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常
> > 
> > 
> > 台湾用户富裕，情况还好一点，可以开会员嘛。大陆用户就苦逼了，没钱开会员啊
> 
> 問題是百度盤把台灣ip給牆了

李彦宏这么骚的嘛，不给我们湾湾用，生气，投诉他

**Comment by NIUDEPI** [comment]
XDown噶了。百度网盘超级会员账号能进行共享操作吗？号会不会被干掉

**Comment by ASPG96315** [comment]
状态异常，无法下载

**Comment by kairyfor** [comment]
xdown下载后的文件用360杀毒提示有病毒，安全吗

**Comment by sonicviking** [comment]
提示异常。显示 byte-range-spec must be positive，这怎么解决呢

**Comment by Hugo342523** [comment]
> xdown下载后的文件用360杀毒提示有病毒，安全吗

把360卸载掉就行了。只要Windows defender不报毒就没事

**Comment by abc598300612** [comment]
> > > 台灣用戶 不管是下載助手的直連連結還是在線解析的連結都顯示異常
> > 
> > 
> > 台湾用户富裕，情况还好一点，可以开会员嘛。大陆用户就苦逼了，没钱开会员啊
> 
> 問題是百度盤把台灣ip給牆了

这么骚，不过人家台湾用户本来就在墙外 倒是也不需要画蛇添足跑回墙内搞资源

**Comment by abc598300612** [comment]
> XDown噶了。百度网盘超级会员账号能进行共享操作吗？号会不会被干掉
你要肿么共享，分享链接吗

**Comment by Cdners** [comment]
vps上装 Aria2 ， 用这个提取的链接下载可行么？

**Comment by MU0UM** [comment]
下载速度只有30k是怎么回事，用百度网盘的下载速度都远大于这个数字

**Comment by abc598300612** [comment]
> 下载速度只有30k是怎么回事，用百度网盘的下载速度都远大于这个数字

我已经放弃了 前两天搞活动 交月供了

**Comment by striver8** [comment]
使用xdown下载直接异常了，不能下载，idm只有4个县城，100k

**Comment by wiixiiidi** [comment]
> @striver8
> 使用xdown下载直接异常了，不能下载，idm只有4个县城，100k

我也是异常

**Comment by hecanqq** [comment]
xdown有api吗，想用自己的代码调用xdown下载文件

**Comment by pp605** [comment]
总是显示异常。。。恼火！！

**Comment by mengzhisha** [comment]
显示异常+1

**Comment by we2xrs** [comment]
为什么我的下载速度还是好慢啊

**Comment by kai2428909167** [comment]
没有看到免登陆下载

**Comment by xixiahuahuo** [comment]
我改了下载地址就下载异常了

**Comment by 15516018** [comment]
怎么没有反应啦

**Comment by sususu777** [comment]
总是在下载更新包，为什么这一步无法跨越？

**Comment by xiaolijian916** [comment]
2020-02-14，测试百度盘下载正常，但是磁力链接一直解析不出来，卡在【正在获取磁链...】,这是为什么呀

**Comment by suken1017** [comment]
我怎么显示复制全部链接后点ok不弹出界面，idm也不弹出

**Comment by momandaic** [comment]
请问为什么下载的时候一直都是异常呢

**Comment by haodan188** [comment]
大佬大佬，想问下，开始xdown能下载，再下载的时候就异常了，请问是咋么回事

**Comment by haodan188** [comment]
> @momandaic
> 请问为什么下载的时候一直都是异常呢

同样的问题，但是我开始是能下载的

**Comment by f4nff** [comment]
异常的话，等一会，手动启动一下，

**Comment by circlelinesss** [comment]
我用xdown下载显示状态异常怎么破解？

**Comment by a839786670** [comment]
下载异常

**Comment by renyuan233** [comment]
下载异常怎么办，重启等一会都不行，用xdown

**Comment by PIinkmanHu** [comment]
> @renyuan233
> 下载异常怎么办，重启等一会都不行，用xdown

xdown看样子是挂了

**Comment by SuenChi** [comment]
刚下载好时速度挺快的，但现在下载大文件总是显示异常（已开会员），这该咋办呢

**Comment by hanmi** [comment]
已经用不了了

**Comment by MODcraft666** [comment]
备用连接提示，文件过小，请下载客户端或购买VIP，服了哈哈

**Comment by ikehu49** [comment]
使用xdown一直显示异常，用IDM在分享页无法下载大文件，在自己网盘里则显示“拦截了根据baidupcs.com......"。 请问现在有哪种方法是可用且稳定的呢？

**Comment by MODcraft666** [comment]
> 使用xdown一直显示异常，用IDM在共享页无法下载大文件，在自己的网盘里则显示“拦截了根据baidupcs.com ......”。请问现在有哪种方法是可用且稳定的呢？

我买了VIP，一切都正常了.....

**Comment by ikehu49** [comment]
> @MODcraft666
> > 使用xdown一直显示异常，用IDM在共享页无法下载大文件，在自己的网盘里则显示“拦截了根据baidupcs.com ......”。请问现在有哪种方法是可用且稳定的呢？
> 
> 我买了VIP，一切都正常了.....

一直都是超级会员，以前都还好，最近啥都不能用了😓

**Comment by ssgnh** [comment]
为什么我这显示链接里没有“复制全部链接”选项

**Comment by MODcraft666** [comment]
> 为什么我这显示链接里没有“复制全部链接”选项

截图解决一切

**Comment by ssgnh** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MODcraft"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 中午11:24
收件人: "syhyz1990/baiduyun"<baiduyun@noreply.github.com&gt;; 
抄送: "伐木丁丁（zhēng）"<1594924852@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [syhyz1990/baiduyun] XDown 使用技巧 | 百度网盘直链下载助手 (#269)





  
为什么我这显示链接里没有“复制全部链接”选项
  
截图解决一切
